package com.rmsproject.restaurant_management_system.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

// ============================================================
// User.java — Entity for ALL users in the system
// DB Table: users
//
// Covers: customer, chef, cashier, manager, admin
// Role stored as uppercase string: CUSTOMER, CHEF, CASHIER,
//   MANAGER, ADMIN
// Status: ACTIVE or INACTIVE
// employee_id: only set for staff (chef/cashier/manager/admin)
//   auto-generated by admin when hiring, null for customers
// shift: only set for staff, null for customers
//   set at hire time, NEVER editable after
// date_of_birth: only for customers (birthday feature)
// created_at: auto-set on INSERT, never changed
// ============================================================

@Entity
@Table(name = "users")
public class User {

    // ── PRIMARY KEY ───────────────────────────────────────────
    // UUID auto-generated by Spring/Hibernate — never manual
    // DB: UNIQUEIDENTIFIER type in SQL Server
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "user_id", updatable = false, nullable = false,
            columnDefinition = "UNIQUEIDENTIFIER")
    private UUID userId;

    // ── CORE FIELDS (all roles) ───────────────────────────────
    @Column(nullable = false)
    private String name;

    // Unique — used as username for login
    @Column(nullable = false, unique = true)
    private String email;

    @Column
    private String phone;

    // BCrypt hashed — never stored plain
    @Column(nullable = false)
    private String password;

    // Values: CUSTOMER, CHEF, CASHIER, MANAGER, ADMIN
    // Uppercase — matches Spring Security .roles() expectation
    @Column(nullable = false)
    private String role;

    // Values: ACTIVE, INACTIVE
    // Checked on login — INACTIVE users cannot login
    @Column(nullable = false)
    private String status = "ACTIVE";

    // Auto-set on record creation
    // DB: DEFAULT GETDATE() in SQL Server
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    // ── EMPLOYEE-ONLY FIELDS ──────────────────────────────────
    // Set by admin on hire — null for customers

    // Auto-generated by admin system on hire
    // Format: EMP-XXXX (UUID-based random)
    // Never editable after set
    @Column(name = "employee_id", unique = true)
    private String employeeId;

    // Values: Morning, Evening
    // Set ONCE at hire — NEVER editable after
    // Admin cannot change shift through edit employee form
    @Column(name = "shift")
    private String shift;

    // ── CUSTOMER-ONLY FIELDS ──────────────────────────────────
    // null for staff

    // Used for birthday balloon animation + age calculation
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    // ── LIFECYCLE HOOKS ───────────────────────────────────────

    // Auto-set createdAt before first INSERT
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        // Ensure status defaults to ACTIVE if not set
        if (this.status == null) {
            this.status = "ACTIVE";
        }
    }

    // ── GETTERS & SETTERS ─────────────────────────────────────

    public UUID getUserId() { return userId; }
    public void setUserId(UUID userId) { this.userId = userId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getCreatedAt() { return createdAt; }

    public String getEmployeeId() { return employeeId; }
    public void setEmployeeId(String employeeId) { this.employeeId = employeeId; }

    public String getShift() { return shift; }
    public void setShift(String shift) { this.shift = shift; }

    public LocalDate getDateOfBirth() { return dateOfBirth; }
    public void setDateOfBirth(LocalDate dateOfBirth) { this.dateOfBirth = dateOfBirth; }
}